### ISSUE TITLE
Resolve 301 and 302 redirects in article.api

### ISSUE THREAD

**Issue by kristjanmik** [vthorsteinsson/Reynir#54]
The article.api does not understand redirects and returns an error.
```
Eftirfarandi villa kom upp: 'NoneType' object has no attribute 'domain'
```

## Steps to reproduce
**Returns a valid response(http):**
```curl -d "url=http://www.ruv.is/frett/segir-nafn-svavars-gudnasonar-eydilagt" https://greynir.is/article.api/v1```

**Returns an invalid response(https):**
```curl -d "url=https://www.ruv.is/frett/segir-nafn-svavars-gudnasonar-eydilagt" https://greynir.is/article.api/v1```

Note that the URL is an example taken from https://greynir.is/apidoc.

**Comment by vthorsteinsson** [comment]
Solved. The problem was not 301/302 redirects but an SSL certificate verification error when requesting `https://www.ruv.is` (also visible when trying `curl https://www.ruv.is/frett/segir-nafn-svavars-gudnasonar-eydilagt` directly). Greynir now returns a reasonable error message saying that the article could not be fetched.
